name: Release Allep

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create allep file
        uses: vimtor/action-zip@v1.2
        with:
          files: Library/ PythonPartsScripts/ install-config.yml requirements.in
          recursive: false
          dest: PythonPartsFr.allep

      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          $notes = "### Release notes $tag`n"
          
          gh release create "$tag" `
            --title "ALLPLAN FRANCE PythonParts Collection v$tag" `            
            --draft `
            --notes "$notes" `
            PythonPartsFr.allep
